### PR TITLE
Testing and debugging graph generation

### PR DESCRIPTION
**Pull request by egor-bogomolov**
Previously, the graph generation did not handle some cases (failed with errors / failed asserts / incorrect graphs). This PR adds tests for graph generation and fixes several issues that were found during testing.

### The structure of tests:
1. Several manually crafted tests, targeting tricky cases (decorators, annotated subscripts, chained assignments,...)
2. A corpus of [120 repositories](src/data_preparation/test_data/repositories_list.txt) with about 36K Python files, for which we check that graph generation doesn't fail and run basic sanity checks (e.g., that occurrences actually refer to the same variable or there are no missing `NEXT` edges).

### What was fixed:
1. Functions with decorators failed generation with an error. It happened because ast/typed_ast points function to the line with its first decorator, while symbol tables point to the line with `def`. To handle it, we now find the first function in the symbol table with matching name and type that has a line number greater or equal than the AST's one. If there are no such functions, we use the closest matching one.
2. The same thing happened with comprehensions (list, dict, set, generators), but the other way around. AST can point to the line which is after the symbol table's one. For them, we find the closest predecessor.
3. When there are several lambdas on the same line, and one of them creates another scope of visibility (e.g., it has a nested lambda, ugly, but happens sometimes), the generator didn't find the proper symbol table. To fix it, we count the number of times each symbol table was used, and pick the one that was used fewer times (all of it for symbol tables on the same line). It fixes the lambda-case, because we then pick the tables one by one. It seems like in this case we won't ask for the same table multiple times in a row, so I hope that it works fine.
4. Chained assignments caused an incorrect representation: they were either skipped with an error (when they had a comment annotation) or transformed into tuple (`a = b = c = func()` -> `(a, b, c,) = func()`). Now they are handled correctly and do not fail generation.
5. Type annotation for subscript (e.g., `d['int_field']: int = 4`) caused a fail in the generator. Now it is parsed correctly, but the annotation is skipped since it is hard to connect it with any symbol.
6. Incorrect syntax (python2 files) or non-unicode symbols are skipped.

### Yet to be done:
* CI integration for tests. Should we run sanity checks on a smaller version of this 120-repos dataset? For 36K files, it takes about 30 minutes to run them locally.
* Extend the sanity checks to other types of edges.
* Tests for other parts of the pipeline.

### P.S
* There are many changed files because I changed the structure of imports to run tests. 
* I've got no idea why GitHub thinks that `graphgenerator.py` was completely changed. In fact, there are only a handful of functions that were modified.

### CODE REVIEW

**Comment by bzz** [comment]
❤️ looks awesome!

> I've got no idea why GitHub thinks that graphgenerator.py was completely changed

I believe this has to do with the platform-specific line-ending 🙈  

Ignoring those with `git diff -w` equivalent shows actual changes alright https://github.com/JetBrains-Research/typilus/pull/1/files?w=1

**Comment by egor-bogomolov** [comment]
Never thought about it, thanks!

**Comment by bzz** [comment]
Looks great to me and seems to address everything from https://github.com/typilus/typilus/issues/5 💪 🥇

**Comment by egor-bogomolov** [comment]
Can I merge it then?

**Comment by bzz** [comment]
Let's :shipit: !

**Pull request merged**
